server:
  port: 8282

configuracion:
  texto: Configuracion de entorno por defecto
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/s08_exp_practica02_security?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: cjava
    password: cjavaeugenio2021
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect