server:
  port: 8283

configuracion:
  texto: Configuracion de entorno de produccion
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cjava_usuarios?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: cjava
    password: cjavaeugenio2021